version: '3' 

services: 
    neo4j: 
        image: neo4j:latest 
        container_name: neo4j
        #network_mode: "bridge" 
        ports: 
            - "7476:7474" 
            - "7689:7687" 
        environment: 
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.* 
            - NEO4J_dbms_security_procedures_whitelist=apoc.*,algo.* 
            - NEO4J_apoc_import_file_enabled=true 
            - NEO4J_dbms_shell_enabled=true 
            #- NEO4JLABS_PLUGINS=["apoc", "graph-algorithms"] 
        volumes: 
            - ./volume/plugins:/plugins 
            - ./volume/data:/data 
            - ./volume/import:/import
    python:
        build: .
        links:
            - neo4j